/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as DiscussionsIdRouteImport } from './routes/discussions.$id'
import { Route as ProjectsSlugEditRouteImport } from './routes/projects.$slug.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsIdRoute = DiscussionsIdRouteImport.update({
  id: '/discussions/$id',
  path: '/discussions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugEditRoute = ProjectsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/developers': typeof DevelopersRoute
  '/for-companies': typeof ForCompaniesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/developers': typeof DevelopersRoute
  '/for-companies': typeof ForCompaniesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/developers': typeof DevelopersRoute
  '/for-companies': typeof ForCompaniesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/developers'
    | '/for-companies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/discussions/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/profile/$handle'
    | '/projects/$slug'
    | '/projects/new'
    | '/spaces/$slug'
    | '/opportunities/'
    | '/projects/'
    | '/spaces/'
    | '/projects/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/developers'
    | '/for-companies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/discussions/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/profile/$handle'
    | '/projects/$slug'
    | '/projects/new'
    | '/spaces/$slug'
    | '/opportunities'
    | '/projects'
    | '/spaces'
    | '/projects/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/developers'
    | '/for-companies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/discussions/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/profile/$handle'
    | '/projects/$slug'
    | '/projects/new'
    | '/spaces/$slug'
    | '/opportunities/'
    | '/projects/'
    | '/spaces/'
    | '/projects/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DevelopersRoute: typeof DevelopersRoute
  ForCompaniesRoute: typeof ForCompaniesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  DiscussionsIdRoute: typeof DiscussionsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/$id': {
      id: '/discussions/$id'
      path: '/discussions/$id'
      fullPath: '/discussions/$id'
      preLoaderRoute: typeof DiscussionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/edit': {
      id: '/projects/$slug/edit'
      path: '/edit'
      fullPath: '/projects/$slug/edit'
      preLoaderRoute: typeof ProjectsSlugEditRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface ProjectsSlugRouteChildren {
  ProjectsSlugEditRoute: typeof ProjectsSlugEditRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugEditRoute: ProjectsSlugEditRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DevelopersRoute: DevelopersRoute,
  ForCompaniesRoute: ForCompaniesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  DiscussionsIdRoute: DiscussionsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  SpacesSlugRoute: SpacesSlugRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SpacesIndexRoute: SpacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
