/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as DiscussionsIdRouteImport } from './routes/discussions.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpacesRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const DiscussionsIdRoute = DiscussionsIdRouteImport.update({
  id: '/discussions/$id',
  path: '/discussions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/developers': typeof DevelopersRoute
  '/for-companies': typeof ForCompaniesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/terms': typeof TermsRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/developers': typeof DevelopersRoute
  '/for-companies': typeof ForCompaniesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/terms': typeof TermsRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/developers': typeof DevelopersRoute
  '/for-companies': typeof ForCompaniesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/terms': typeof TermsRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/developers'
    | '/for-companies'
    | '/login'
    | '/onboarding'
    | '/opportunities'
    | '/privacy'
    | '/projects'
    | '/search'
    | '/spaces'
    | '/terms'
    | '/discussions/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/profile/$handle'
    | '/projects/$slug'
    | '/projects/new'
    | '/spaces/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/developers'
    | '/for-companies'
    | '/login'
    | '/onboarding'
    | '/opportunities'
    | '/privacy'
    | '/projects'
    | '/search'
    | '/spaces'
    | '/terms'
    | '/discussions/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/profile/$handle'
    | '/projects/$slug'
    | '/projects/new'
    | '/spaces/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/developers'
    | '/for-companies'
    | '/login'
    | '/onboarding'
    | '/opportunities'
    | '/privacy'
    | '/projects'
    | '/search'
    | '/spaces'
    | '/terms'
    | '/discussions/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/profile/$handle'
    | '/projects/$slug'
    | '/projects/new'
    | '/spaces/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DevelopersRoute: typeof DevelopersRoute
  ForCompaniesRoute: typeof ForCompaniesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SpacesRoute: typeof SpacesRouteWithChildren
  TermsRoute: typeof TermsRoute
  DiscussionsIdRoute: typeof DiscussionsIdRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/discussions/$id': {
      id: '/discussions/$id'
      path: '/discussions/$id'
      fullPath: '/discussions/$id'
      preLoaderRoute: typeof DiscussionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SpacesRouteChildren {
  SpacesSlugRoute: typeof SpacesSlugRoute
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesSlugRoute: SpacesSlugRoute,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DevelopersRoute: DevelopersRoute,
  ForCompaniesRoute: ForCompaniesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SearchRoute: SearchRoute,
  SpacesRoute: SpacesRouteWithChildren,
  TermsRoute: TermsRoute,
  DiscussionsIdRoute: DiscussionsIdRoute,
  ProfileHandleRoute: ProfileHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
